name: desafio
description: "A new Flutter project."
publish_to: 'none' # Este pacote não será publicado no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.1
  flutter_mobx: ^2.0.1
  firebase_core: ^2.15.0 # Última versão estável
  cloud_firestore: ^4.10.1 # Última versão estável
  provider: ^6.0.1
  firebase_auth: ^4.7.0 # Última versão estável
  logger: ^1.1.0
dev_dependencies:
  build_runner: ^2.1.5
  mobx_codegen: ^2.0.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - imagens/logo.png
